PORTNAME=	flamegraph-l41
PORTVERSION=	20230113
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

USE_GITHUB=	yes
GH_ACCOUNT=	Cambridge-AdvancedOS
GH_PROJECT=	pyflamegraph
GH_TAGNAME=	c0b4bcd57472984c9d15f4f7dcace1466401a29c

MAINTAINER=	konrad.witaszczyk@cl.cam.ac.uk
COMMENT=	Flame Graph library
WWW=		https://github.com/Cambridge-AdvancedOS/pyflamegraph

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
