PORTNAME=	flamegraph-l41
PORTVERSION=	20261003
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

USE_GITHUB=	yes
GH_ACCOUNT=	Cambridge-AdvancedOS
GH_PROJECT=	pyflamegraph
GH_TAGNAME=	76ed5e7cd2b778a02c74d777725c4a9febbc65a1

MAINTAINER=	konrad.witaszczyk@cl.cam.ac.uk
COMMENT=	Flame Graph library
WWW=		https://github.com/Cambridge-AdvancedOS/pyflamegraph

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
