PORTNAME=	flamegraph-l41
PORTVERSION=	20261003
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

USE_GITHUB=	yes
GH_ACCOUNT=	Cambridge-AdvancedOS
GH_PROJECT=	pyflamegraph
GH_TAGNAME=	8d449e6661b712f2590c119ce42e4682e9ecf91d

MAINTAINER=	konrad.witaszczyk@cl.cam.ac.uk
COMMENT=	Flame Graph library
WWW=		https://github.com/Cambridge-AdvancedOS/pyflamegraph

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
